import type { Metadata } from "next";
import "./globals.css";
import RightBar from "@/components/RightBar";
import LeftBar from "@/components/LeftBar";

export const metadata: Metadata = {
  title: "X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa">
      <body>
        <div className="flex justify-between max-w-screen-md lg:max-w-screen-lg xl:max-w-screen-xl 2xl:max-w-screen-2xl mx-auto">
          <aside className="px-2 sm:px-4">
            <RightBar />
          </aside>
          <main className="flex-1 lg:min-w-[600px] border-x-[1px] border-gray-600">
            {children}
            {modal}
          </main>
          <aside className="hidden lg:flex flex-1 mr-4 xl:mr-8">
            <LeftBar />
          </aside>
        </div>
      </body>
    </html>
  );
}
